# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sidekiq-dynamic-queues 0.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "sidekiq-dynamic-queues"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Matt Conway"]
  s.date = "2014-05-01"
  s.email = "matt@conwaysplace.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    ".travis.yml",
    "CHANGELOG",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "config.ru",
    "init.rb",
    "lib/sidekiq-dynamic-queues-server.rb",
    "lib/sidekiq-dynamic-queues.rb",
    "lib/sidekiq/dynamic_queues/attributes.rb",
    "lib/sidekiq/dynamic_queues/fetch.rb",
    "lib/sidekiq/dynamic_queues/server.rb",
    "lib/sidekiq/dynamic_queues/server/views/dynamicqueue.erb",
    "lib/sidekiq/dynamic_queues/version.rb",
    "sidekiq-dynamic-queues.gemspec",
    "spec/queues_spec.rb",
    "spec/redis-test.conf",
    "spec/server_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/nedap/sidekiq-dynamic-queues"
  s.rubygems_version = "2.2.2"
  s.summary = "A sidekiq plugin for specifying the queues a worker pulls from with wildcards, negations, or dynamic look up from redis"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sidekiq-dynamic-queues>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<gemfury>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5"])
      s.add_development_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<slim>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, ["~> 0.5.4"])
      s.add_development_dependency(%q<tilt>, ["~> 1.4"])
    else
      s.add_dependency(%q<sidekiq-dynamic-queues>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gemfury>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.5"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<slim>, [">= 0"])
      s.add_dependency(%q<rack-test>, ["~> 0.5.4"])
      s.add_dependency(%q<tilt>, ["~> 1.4"])
    end
  else
    s.add_dependency(%q<sidekiq-dynamic-queues>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gemfury>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.5"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<slim>, [">= 0"])
    s.add_dependency(%q<rack-test>, ["~> 0.5.4"])
    s.add_dependency(%q<tilt>, ["~> 1.4"])
  end
end

